tune_config:
  trial_path: logs
  trial_name: dqn_cartpole
  ray_local_mode: False
  num_cpus:       24
  num_gpus:       0
  ray_num_trial_samples:  3
  cpus_per_worker:        3
  gpus_per_worker:        0

algorithm_config:
  env_id:   "CartPole-v1"


  agent:               DQN
  total_timesteps:    1000
  learning_rate:      0.001
    # - grid_search
    # - float
    # - [0.001, 0.0001]
  num_envs:           1
  buffer_size:        10000
  gamma:              0.99
  tau:                1.0
  target_network_frequency:   5
  batch_size:         16
  start_e:            1
  end_e:              0.01
  exploration_fraction:   0.35
  learning_starts:        1000
  train_frequency:        1
  

  cuda: False

